{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Gateway\n",
    "deeplearning.net\n",
    "http://deeplearning.net/\n",
    "<br>\n",
    "arXiv.org\n",
    "https://arxiv.org/\n",
    "<br>\n",
    "reddit! Machine Learning\n",
    "https://www.reddit.com/r/MachineLearning/\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Courses\n",
    "Stanford CS229: Machine Learning\n",
    "http://cs229.stanford.edu/\n",
    "<br>\n",
    "Stanford CS231n: Convolutional Neural Networks for Visual Recognition\n",
    "http://vision.stanford.edu/teaching/cs231n/index.html\n",
    "<br>\n",
    "Stanford CS224d: Deep Learning for Natural Language Processing\n",
    "http://cs224d.stanford.edu/index.html\n",
    "<br>\n",
    "Stanford CS20SI: Tensorflow for Deep Learning Research\n",
    "http://web.stanford.edu/class/cs20si/index.html\n",
    "<br>\n",
    "MIT 6.S094: Deep Learning for Self-driving Cars\n",
    "http://selfdrivingcars.mit.edu/\n",
    "<br>\n",
    "MIT 6.S191: Introduction to Deep Learning\n",
    "http://introtodeeplearning.com/\n",
    "<br>\n",
    "UCB CS294: Deep Reinforcement Learning \n",
    "http://rll.berkeley.edu/deeprlcourse/\n",
    "<br>\n",
    "Coursera Neural Networks for Machine Learning by Geoffrey Hinton\n",
    "https://www.coursera.org/learn/neural-networks\n",
    "<br>\n",
    "Udacity Deep Learning by Google\n",
    "https://www.udacity.com/course/deep-learning--ud730\n",
    "<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Tutorials\n",
    "\n",
    "Jupyter Notebook Tutorial: The Definitive Guide\n",
    "https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook#gs.08xnsGo\n",
    "<br>\n",
    "Python Machine Learning Mini-course\n",
    "http://machinelearningmastery.com/python-machine-learning-mini-course/\n",
    "<br>\n",
    "Learn Tensorflow and deep learning, without a Ph.D.\n",
    "https://cloud.google.com/blog/big-data/2017/01/learn-tensorflow-and-deep-learning-without-a-phd\n",
    "<br>\n",
    "Understanding neural networks with TensorFlow Playground\n",
    "https://cloud.google.com/blog/big-data/2016/07/understanding-neural-networks-with-tensorflow-playground\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Video Lectures\n",
    "Deep learning summer school, Montreal 2016\n",
    "http://videolectures.net/deeplearning2016_montreal/\n",
    "<br>\n",
    "Deep learning summer school, Montreal 2015\n",
    "http://videolectures.net/deeplearning2015_montreal/\n",
    "<br>\n",
    "TensorFlow Dev Summit 2017\n",
    "https://www.youtube.com/playlist?list=PLOU2XLYxmsIKGc_NBoIhTn2Qhraji53cv\n",
    "<br>\n",
    "Google I/O 2017\n",
    "https://www.youtube.com/playlist?list=PLOU2XLYxmsIKC8eODk_RNCWv3fBcLvMMy\n",
    "<br>\n",
    "Deep learning by Yann Lecun\n",
    "https://www.college-de-france.fr/site/en-yann-lecun/course-2015-2016.htm\n",
    "<br>\n",
    "Bay Area Deep Learning School 2016 <br>\n",
    "Day 1 https://www.youtube.com/watch?v=eyovmAtoUx0\n",
    "<br>\n",
    "Day 2 https://www.youtube.com/watch?v=9dXiAecyJrY\n",
    "<br>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Datasets\n",
    "#### General\n",
    "Deep Learning datasets\n",
    "http://deeplearning.net/datasets/\n",
    "<br>\n",
    "Kaggle datasets\n",
    "https://www.kaggle.com/datasets\n",
    "<br>\n",
    "UCI machine learning repository\n",
    "https://archive.ics.uci.edu/ml/datasets.html\n",
    "<br>\n",
    "reddit datasets\n",
    "https://www.reddit.com/r/datasets/\n",
    "<br>\n",
    "Datasets for data mining and data science (short descriptions)\n",
    "http://www.kdnuggets.com/datasets/index.html\n",
    "<br>\n",
    "re3data (research)\n",
    "http://www.re3data.org/\n",
    "<br>\n",
    "\n",
    "#### Image\n",
    "ImageNet\n",
    "http://image-net.org/index\n",
    "<br>\n",
    "CIFAR-10 & CIFAR-100\n",
    "http://www.cs.toronto.edu/~kriz/cifar.html\n",
    "<br>\n",
    "places: The scene recognition database\n",
    "http://places.csail.mit.edu/\n",
    "<br>\n",
    "MNIST handwritten digits\n",
    "http://yann.lecun.com/exdb/mnist/\n",
    "\n",
    "#### Motion\n",
    "CMU Graphics Lab Motion Capture Database\n",
    "http://mocap.cs.cmu.edu/\n",
    "<br>\n",
    "\n",
    "#### Text & Language\n",
    "WordNet\n",
    "http://wordnet.princeton.edu/\n",
    "<br>\n",
    "\n",
    "#### Society\n",
    "KAPSARC Data Portal (Energy)\n",
    "https://datasource.kapsarc.org/pages/home/\n",
    "<br>\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Blogs\n",
    "colah's blog\n",
    "https://colah.github.io/\n",
    "<br>\n",
    "Domino Data Science Blog\n",
    "https://blog.dominodatalab.com/tag/python/\n",
    "<br>\n",
    "Machine Learning is Fun!\n",
    "https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471\n",
    "<br>\n",
    "Machine Learning: An In-Depth Guide\n",
    "http://www.innoarchitech.com/machine-learning-an-in-depth-non-technical-guide/\n",
    "<br>\n",
    "Machine Learning Mastery\n",
    "http://machinelearningmastery.com/\n",
    "<br>\n",
    "Andrej Karpathy blog\n",
    "http://karpathy.github.io/\n",
    "<br>\n",
    "Adit Deshpande blog\n",
    "https://adeshpande3.github.io/adeshpande3.github.io/\n",
    "<br>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Korean 한국어\n",
    "모두를 위한 머신러닝/딥러닝 강의\n",
    "http://hunkim.github.io/ml/\n",
    "<br>\n",
    "SanghyukChun's Blog\n",
    "http://sanghyukchun.github.io/\n",
    "<br>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Web\n",
    "\n",
    "A visual introduction to machine learning\n",
    "http://www.r2d3.us/visual-intro-to-machine-learning-part-1/\n",
    "<br>\n",
    "Tensorflow Playground\n",
    "http://playground.tensorflow.org\n",
    "<br>\n",
    "ConvNetJS 2d classification demo\n",
    "http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html\n",
    "<br>\n",
    "ConvNetJS CIFAR-10 demo\n",
    "http://cs.stanford.edu/people/karpathy/convnetjs/demo/cifar10.html\n",
    "<br>\n",
    "Linear classification loss visualization\n",
    "http://vision.stanford.edu/teaching/cs231n-demos/linear-classify/\n",
    "<br>\n",
    "t-SNE visualization of CNN codes\n",
    "http://cs.stanford.edu/people/karpathy/cnnembed/\n",
    "<br>\n",
    "Four Experiments in Handwriting with a Neural Network\n",
    "http://distill.pub/2016/handwriting/\n",
    "<br>\n",
    "Recurrent neural network handwriting generation demo\n",
    "http://www.cs.toronto.edu/~graves/handwriting.cgi\n",
    "<br>\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
